// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtu4KK2y0evPyCDYGXAbhUDqdCIyqEDJQ',
    appId: '1:500107115137:web:4cbef3dda9cf5fc4ffeb80',
    messagingSenderId: '500107115137',
    projectId: 'to-do-flutter-d9f58',
    authDomain: 'to-do-flutter-d9f58.firebaseapp.com',
    storageBucket: 'to-do-flutter-d9f58.firebasestorage.app',
    measurementId: 'G-NWX9KC92LH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYqOm-euyIW285MXLDNmkRwMR_e1ZaRYs',
    appId: '1:500107115137:android:b625220c52e1e01affeb80',
    messagingSenderId: '500107115137',
    projectId: 'to-do-flutter-d9f58',
    storageBucket: 'to-do-flutter-d9f58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-nSeP0uaJmlYk2GMrxto228HWClG5wC8',
    appId: '1:500107115137:ios:1d78d57baeba70d3ffeb80',
    messagingSenderId: '500107115137',
    projectId: 'to-do-flutter-d9f58',
    storageBucket: 'to-do-flutter-d9f58.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-nSeP0uaJmlYk2GMrxto228HWClG5wC8',
    appId: '1:500107115137:ios:1d78d57baeba70d3ffeb80',
    messagingSenderId: '500107115137',
    projectId: 'to-do-flutter-d9f58',
    storageBucket: 'to-do-flutter-d9f58.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtu4KK2y0evPyCDYGXAbhUDqdCIyqEDJQ',
    appId: '1:500107115137:web:baa2b145369dfa56ffeb80',
    messagingSenderId: '500107115137',
    projectId: 'to-do-flutter-d9f58',
    authDomain: 'to-do-flutter-d9f58.firebaseapp.com',
    storageBucket: 'to-do-flutter-d9f58.firebasestorage.app',
    measurementId: 'G-3FLNHQG4Q0',
  );

}